In [1]:
!pip install openpyxl

Requirement already satisfied: openpyxl in /Users/sumiya/opt/anaconda3/lib/python3.8/site-packages (3.0.4)
Requirement already satisfied: et-xmlfile in /Users/sumiya/opt/anaconda3/lib/python3.8/site-packages (from openpyxl) (1.0.1)
Requirement already satisfied: jdcal in /Users/sumiya/opt/anaconda3/lib/python3.8/site-packages (from openpyxl) (1.4.1)

In [2]:
import openpyxl
import pandas as pd
import glob

In [3]:
import_file_path = '/Users/sumiya/Documents/programming/python-study/2021/05/20/sample.xlsx'
excel_sheet_name = '資産形成'
export_file_path = '/Users/sumiya/Documents/programming/python-study/2021/05/20/output'

In [4]:
df_order = pd.read_excel(import_file_path, sheet_name = excel_sheet_name)

In [5]:
df_order

,年月,Unnamed: 1,貯金額合計,手取り月収,額面収入,健康保険,厚生年金,雇用保険,所得税,持株会,...,家賃,実家,交際費,飲食代,交通費,固定費,衣料費,その他,特例費用,旅行
0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-04-01,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1479.0,2629.0,3000.0,4168.0,3250.0,5500.0,0.0,0.0
2,2020-05-01,NaN,213748.0,267474.0,318750.0,13600.0,29280.0,956.0,7440.0,0.0,...,0.0,30000.0,5000.0,8668.0,3000.0,4168.0,0.0,2890.0,0.0,0.0
3,2020-06-01,NaN,391163.0,267474.0,318750.0,13600.0,29280.0,956.0,7440.0,0.0,...,0.0,30000.0,16100.0,18091.0,9000.0,4168.0,12700.0,0.0,0.0,0.0
4,2020-07-01,NaN,507809.0,237364.0,321750.0,13600.0,29280.0,956.0,7550.0,33000.0,...,0.0,30000.0,33090.0,35815.0,12000.0,3168.0,850.0,5795.0,0.0,0.0
5,2020-08-01,NaN,625280.0,237364.0,321750.0,13600.0,29280.0,956.0,7550.0,33000.0,...,0.0,15000.0,2200.0,36385.0,56410.0,3168.0,6730.0,NaN,0.0,0.0
6,2020-09-01,NaN,742263.0,237364.0,321750.0,13600.0,29280.0,956.0,7550.0,33000.0,...,0.0,15000.0,51000.0,41015.0,6000.0,3168.0,0.0,4198.0,0.0,0.0
7,2020-10-01,NaN,870627.0,237364.0,321750.0,13600.0,29280.0,956.0,7550.0,33000.0,...,100000.0,NaN,NaN,NaN,9000.0,NaN,NaN,NaN,NaN,NaN
8,2020-11-01,NaN,989991.0,237364.0,321750.0,13600.0,29280.0,956.0,7550.0,33000.0,...,100000.0,NaN,NaN,NaN,18000.0,NaN,NaN,NaN,NaN,NaN
9,2020-12-01,NaN,1127355.0,237364.0,321750.0,13600.0,29280.0,956.0,7550.0,33000.0,...,100000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2021-01-01,NaN,1264719.0,237364.0,321750.0,13600.0,29280.0,956.0,7550.0,33000.0,...,100000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2021-02-01,NaN,902083.0,237364.0,321750.0,13600.0,29280.0,956.0,7550.0,33000.0,...,100000.0,500000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2021-03-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2021-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2021-05-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2021-06-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2021-07-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2021-08-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2021-09-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2021-10-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2021-11-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,2021-12-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,2022-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2022-02-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2022-03-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2022-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2022-05-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2022-06-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2022-07-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,2022-08-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,2022-09-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,2022-10-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,2022-11-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,2022-12-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,2023-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,2023-02-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,2023-03-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,2023-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,2023-05-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,2023-06-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,2023-07-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,2023-08-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,2023-09-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,2023-10-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,2023-11-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,2023-12-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,2024-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,2024-02-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,2024-03-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,2024-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,2024-05-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,2024-06-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,2024-07-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,2024-08-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,2024-09-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,2024-10-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,2024-11-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,2024-12-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
date = df_order['年月'].unique()

In [14]:
date

array([                          'NaT', '2020-04-01T00:00:00.000000000',
       '2020-05-01T00:00:00.000000000', '2020-06-01T00:00:00.000000000',
       '2020-07-01T00:00:00.000000000', '2020-08-01T00:00:00.000000000',
       '2020-09-01T00:00:00.000000000', '2020-10-01T00:00:00.000000000',
       '2020-11-01T00:00:00.000000000', '2020-12-01T00:00:00.000000000',
       '2021-01-01T00:00:00.000000000', '2021-02-01T00:00:00.000000000',
       '2021-03-01T00:00:00.000000000', '2021-04-01T00:00:00.000000000',
       '2021-05-01T00:00:00.000000000', '2021-06-01T00:00:00.000000000',
       '2021-07-01T00:00:00.000000000', '2021-08-01T00:00:00.000000000',
       '2021-09-01T00:00:00.000000000', '2021-10-01T00:00:00.000000000',
       '2021-11-01T00:00:00.000000000', '2021-12-01T00:00:00.000000000',
       '2022-01-01T00:00:00.000000000', '2022-02-01T00:00:00.000000000',
       '2022-03-01T00:00:00.000000000', '2022-04-01T00:00:00.000000000',
       '2022-05-01T00:00:00.000000000', '2022-06-01T00:00:00.000000000',
       '2022-07-01T00:00:00.000000000', '2022-08-01T00:00:00.000000000',
       '2022-09-01T00:00:00.000000000', '2022-10-01T00:00:00.000000000',
       '2022-11-01T00:00:00.000000000', '2022-12-01T00:00:00.000000000',
       '2023-01-01T00:00:00.000000000', '2023-02-01T00:00:00.000000000',
       '2023-03-01T00:00:00.000000000', '2023-04-01T00:00:00.000000000',
       '2023-05-01T00:00:00.000000000', '2023-06-01T00:00:00.000000000',
       '2023-07-01T00:00:00.000000000', '2023-08-01T00:00:00.000000000',
       '2023-09-01T00:00:00.000000000', '2023-10-01T00:00:00.000000000',
       '2023-11-01T00:00:00.000000000', '2023-12-01T00:00:00.000000000',
       '2024-01-01T00:00:00.000000000', '2024-02-01T00:00:00.000000000',
       '2024-03-01T00:00:00.000000000', '2024-04-01T00:00:00.000000000',
       '2024-05-01T00:00:00.000000000', '2024-06-01T00:00:00.000000000',
       '2024-07-01T00:00:00.000000000', '2024-08-01T00:00:00.000000000',
       '2024-09-01T00:00:00.000000000', '2024-10-01T00:00:00.000000000',
       '2024-11-01T00:00:00.000000000', '2024-12-01T00:00:00.000000000'],
      dtype='datetime64[ns]')

In [8]:
type(date)

numpy.ndarray

In [9]:
type(df_order)

pandas.core.frame.DataFrame

In [10]:
df_order['年月'] == '2023-11-01T00:00:00.000000000'

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44     True
45    False
46    False
47    False
48    False
49    False
50    False
51    False
52    False
53    False
54    False
55    False
56    False
57    False
Name: 年月, dtype: bool

In [11]:
df_order[df_order['年月'] == '2023-11-01T00:00:00.000000000']

,年月,Unnamed: 1,貯金額合計,手取り月収,額面収入,健康保険,厚生年金,雇用保険,所得税,持株会,...,家賃,実家,交際費,飲食代,交通費,固定費,衣料費,その他,特例費用,旅行
44,2023-11-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
for i in date:
    df_order_date = df_order[df_order['年月'] == i]
    print(df_order_date)

Empty DataFrame
Columns: [年月, Unnamed: 1, 貯金額合計, 手取り月収, 額面収入, 健康保険, 厚生年金, 雇用保険, 所得税, 持株会, 月貯金額, 余剰貯金, 旅行貯金, 家賃貯金, Unnamed: 14, 支出合計, 家賃, 実家, 交際費, 飲食代, 交通費, 固定費, 衣料費, その他, 特例費用, 旅行]
Index: []

[0 rows x 26 columns]
          年月  Unnamed: 1  貯金額合計  手取り月収  額面収入  健康保険  厚生年金  雇用保険  所得税  持株会  ...  \
1 2020-04-01         NaN    0.0    0.0   0.0   0.0   0.0   0.0  0.0  0.0  ...

    家賃   実家     交際費     飲食代     交通費     固定費     衣料費     その他  特例費用   旅行
1  0.0  0.0  1479.0  2629.0  3000.0  4168.0  3250.0  5500.0   0.0  0.0

[1 rows x 26 columns]
          年月  Unnamed: 1     貯金額合計     手取り月収      額面収入     健康保険     厚生年金  \
2 2020-05-01         NaN  213748.0  267474.0  318750.0  13600.0  29280.0

    雇用保険     所得税  持株会  ...   家賃       実家     交際費     飲食代     交通費     固定費  衣料費  \
2  956.0  7440.0  0.0  ...  0.0  30000.0  5000.0  8668.0  3000.0  4168.0  0.0

      その他  特例費用   旅行
2  2890.0   0.0  0.0

[1 rows x 26 columns]
          年月  Unnamed: 1     貯金額合計     手取り月収      額面収入     健康保険     厚生年金  \
3 2020-06-01         NaN  391163.0  267474.0  318750.0  13600.0  29280.0

    雇用保険     所得税  持株会  ...   家賃       実家      交際費      飲食代     交通費     固定費  \
3  956.0  7440.0  0.0  ...  0.0  30000.0  16100.0  18091.0  9000.0  4168.0

       衣料費  その他  特例費用   旅行
3  12700.0  0.0   0.0  0.0

[1 rows x 26 columns]
          年月  Unnamed: 1     貯金額合計     手取り月収      額面収入     健康保険     厚生年金  \
4 2020-07-01         NaN  507809.0  237364.0  321750.0  13600.0  29280.0

    雇用保険     所得税      持株会  ...   家賃       実家      交際費      飲食代      交通費  \
4  956.0  7550.0  33000.0  ...  0.0  30000.0  33090.0  35815.0  12000.0

      固定費    衣料費     その他  特例費用   旅行
4  3168.0  850.0  5795.0   0.0  0.0

[1 rows x 26 columns]
          年月  Unnamed: 1     貯金額合計     手取り月収      額面収入     健康保険     厚生年金  \
5 2020-08-01         NaN  625280.0  237364.0  321750.0  13600.0  29280.0

    雇用保険     所得税      持株会  ...   家賃       実家     交際費      飲食代      交通費  \
5  956.0  7550.0  33000.0  ...  0.0  15000.0  2200.0  36385.0  56410.0

      固定費     衣料費  その他  特例費用   旅行
5  3168.0  6730.0  NaN   0.0  0.0

[1 rows x 26 columns]
          年月  Unnamed: 1     貯金額合計     手取り月収      額面収入     健康保険     厚生年金  \
6 2020-09-01         NaN  742263.0  237364.0  321750.0  13600.0  29280.0

    雇用保険     所得税      持株会  ...   家賃       実家      交際費      飲食代     交通費  \
6  956.0  7550.0  33000.0  ...  0.0  15000.0  51000.0  41015.0  6000.0

      固定費  衣料費     その他  特例費用   旅行
6  3168.0  0.0  4198.0   0.0  0.0

[1 rows x 26 columns]
          年月  Unnamed: 1     貯金額合計     手取り月収      額面収入     健康保険     厚生年金  \
7 2020-10-01         NaN  870627.0  237364.0  321750.0  13600.0  29280.0

    雇用保険     所得税      持株会  ...        家賃  実家  交際費  飲食代     交通費  固定費  衣料費  その他  \
7  956.0  7550.0  33000.0  ...  100000.0 NaN  NaN  NaN  9000.0  NaN  NaN  NaN

   特例費用  旅行
7   NaN NaN

[1 rows x 26 columns]
          年月  Unnamed: 1     貯金額合計     手取り月収      額面収入     健康保険     厚生年金  \
8 2020-11-01         NaN  989991.0  237364.0  321750.0  13600.0  29280.0

    雇用保険     所得税      持株会  ...        家賃  実家  交際費  飲食代      交通費  固定費  衣料費  \
8  956.0  7550.0  33000.0  ...  100000.0 NaN  NaN  NaN  18000.0  NaN  NaN

   その他  特例費用  旅行
8  NaN   NaN NaN

[1 rows x 26 columns]
          年月  Unnamed: 1      貯金額合計     手取り月収      額面収入     健康保険     厚生年金  \
9 2020-12-01         NaN  1127355.0  237364.0  321750.0  13600.0  29280.0

    雇用保険     所得税      持株会  ...        家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  \
9  956.0  7550.0  33000.0  ...  100000.0 NaN  NaN  NaN  NaN  NaN  NaN  NaN

   特例費用  旅行
9   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1      貯金額合計     手取り月収      額面収入     健康保険     厚生年金  \
10 2021-01-01         NaN  1264719.0  237364.0  321750.0  13600.0  29280.0

     雇用保険     所得税      持株会  ...        家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  \
10  956.0  7550.0  33000.0  ...  100000.0 NaN  NaN  NaN  NaN  NaN  NaN  NaN

    特例費用  旅行
10   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1     貯金額合計     手取り月収      額面収入     健康保険     厚生年金  \
11 2021-02-01         NaN  902083.0  237364.0  321750.0  13600.0  29280.0

     雇用保険     所得税      持株会  ...        家賃        実家  交際費  飲食代  交通費  固定費  衣料費  \
11  956.0  7550.0  33000.0  ...  100000.0  500000.0  NaN  NaN  NaN  NaN  NaN

    その他  特例費用  旅行
11  NaN   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1  貯金額合計  手取り月収  額面収入  健康保険  厚生年金  雇用保険  所得税  持株会  \
12 2021-03-01         NaN    NaN    NaN   NaN   NaN   NaN   NaN  NaN  NaN

    ...  家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  特例費用  旅行
12  ... NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1  貯金額合計  手取り月収  額面収入  健康保険  厚生年金  雇用保険  所得税  持株会  \
13 2021-04-01         NaN    NaN    NaN   NaN   NaN   NaN   NaN  NaN  NaN

    ...  家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  特例費用  旅行
13  ... NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1  貯金額合計  手取り月収  額面収入  健康保険  厚生年金  雇用保険  所得税  持株会  \
14 2021-05-01         NaN    NaN    NaN   NaN   NaN   NaN   NaN  NaN  NaN

    ...  家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  特例費用  旅行
14  ... NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1  貯金額合計  手取り月収  額面収入  健康保険  厚生年金  雇用保険  所得税  持株会  \
15 2021-06-01         NaN    NaN    NaN   NaN   NaN   NaN   NaN  NaN  NaN

    ...  家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  特例費用  旅行
15  ... NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1  貯金額合計  手取り月収  額面収入  健康保険  厚生年金  雇用保険  所得税  持株会  \
16 2021-07-01         NaN    NaN    NaN   NaN   NaN   NaN   NaN  NaN  NaN

    ...  家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  特例費用  旅行
16  ... NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1  貯金額合計  手取り月収  額面収入  健康保険  厚生年金  雇用保険  所得税  持株会  \
17 2021-08-01         NaN    NaN    NaN   NaN   NaN   NaN   NaN  NaN  NaN

    ...  家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  特例費用  旅行
17  ... NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1  貯金額合計  手取り月収  額面収入  健康保険  厚生年金  雇用保険  所得税  持株会  \
18 2021-09-01         NaN    NaN    NaN   NaN   NaN   NaN   NaN  NaN  NaN

    ...  家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  特例費用  旅行
18  ... NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1  貯金額合計  手取り月収  額面収入  健康保険  厚生年金  雇用保険  所得税  持株会  \
19 2021-10-01         NaN    NaN    NaN   NaN   NaN   NaN   NaN  NaN  NaN

    ...  家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  特例費用  旅行
19  ... NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1  貯金額合計  手取り月収  額面収入  健康保険  厚生年金  雇用保険  所得税  持株会  \
20 2021-11-01         NaN    NaN    NaN   NaN   NaN   NaN   NaN  NaN  NaN

    ...  家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  特例費用  旅行
20  ... NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1  貯金額合計  手取り月収  額面収入  健康保険  厚生年金  雇用保険  所得税  持株会  \
21 2021-12-01         NaN    NaN    NaN   NaN   NaN   NaN   NaN  NaN  NaN

    ...  家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  特例費用  旅行
21  ... NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1  貯金額合計  手取り月収  額面収入  健康保険  厚生年金  雇用保険  所得税  持株会  \
22 2022-01-01         NaN    NaN    NaN   NaN   NaN   NaN   NaN  NaN  NaN

    ...  家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  特例費用  旅行
22  ... NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1  貯金額合計  手取り月収  額面収入  健康保険  厚生年金  雇用保険  所得税  持株会  \
23 2022-02-01         NaN    NaN    NaN   NaN   NaN   NaN   NaN  NaN  NaN

    ...  家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  特例費用  旅行
23  ... NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1  貯金額合計  手取り月収  額面収入  健康保険  厚生年金  雇用保険  所得税  持株会  \
24 2022-03-01         NaN    NaN    NaN   NaN   NaN   NaN   NaN  NaN  NaN

    ...  家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  特例費用  旅行
24  ... NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1  貯金額合計  手取り月収  額面収入  健康保険  厚生年金  雇用保険  所得税  持株会  \
25 2022-04-01         NaN    NaN    NaN   NaN   NaN   NaN   NaN  NaN  NaN

    ...  家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  特例費用  旅行
25  ... NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1  貯金額合計  手取り月収  額面収入  健康保険  厚生年金  雇用保険  所得税  持株会  \
26 2022-05-01         NaN    NaN    NaN   NaN   NaN   NaN   NaN  NaN  NaN

    ...  家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  特例費用  旅行
26  ... NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1  貯金額合計  手取り月収  額面収入  健康保険  厚生年金  雇用保険  所得税  持株会  \
27 2022-06-01         NaN    NaN    NaN   NaN   NaN   NaN   NaN  NaN  NaN

    ...  家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  特例費用  旅行
27  ... NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1  貯金額合計  手取り月収  額面収入  健康保険  厚生年金  雇用保険  所得税  持株会  \
28 2022-07-01         NaN    NaN    NaN   NaN   NaN   NaN   NaN  NaN  NaN

    ...  家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  特例費用  旅行
28  ... NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1  貯金額合計  手取り月収  額面収入  健康保険  厚生年金  雇用保険  所得税  持株会  \
29 2022-08-01         NaN    NaN    NaN   NaN   NaN   NaN   NaN  NaN  NaN

    ...  家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  特例費用  旅行
29  ... NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1  貯金額合計  手取り月収  額面収入  健康保険  厚生年金  雇用保険  所得税  持株会  \
30 2022-09-01         NaN    NaN    NaN   NaN   NaN   NaN   NaN  NaN  NaN

    ...  家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  特例費用  旅行
30  ... NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1  貯金額合計  手取り月収  額面収入  健康保険  厚生年金  雇用保険  所得税  持株会  \
31 2022-10-01         NaN    NaN    NaN   NaN   NaN   NaN   NaN  NaN  NaN

    ...  家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  特例費用  旅行
31  ... NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1  貯金額合計  手取り月収  額面収入  健康保険  厚生年金  雇用保険  所得税  持株会  \
32 2022-11-01         NaN    NaN    NaN   NaN   NaN   NaN   NaN  NaN  NaN

    ...  家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  特例費用  旅行
32  ... NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1  貯金額合計  手取り月収  額面収入  健康保険  厚生年金  雇用保険  所得税  持株会  \
33 2022-12-01         NaN    NaN    NaN   NaN   NaN   NaN   NaN  NaN  NaN

    ...  家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  特例費用  旅行
33  ... NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1  貯金額合計  手取り月収  額面収入  健康保険  厚生年金  雇用保険  所得税  持株会  \
34 2023-01-01         NaN    NaN    NaN   NaN   NaN   NaN   NaN  NaN  NaN

    ...  家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  特例費用  旅行
34  ... NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1  貯金額合計  手取り月収  額面収入  健康保険  厚生年金  雇用保険  所得税  持株会  \
35 2023-02-01         NaN    NaN    NaN   NaN   NaN   NaN   NaN  NaN  NaN

    ...  家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  特例費用  旅行
35  ... NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1  貯金額合計  手取り月収  額面収入  健康保険  厚生年金  雇用保険  所得税  持株会  \
36 2023-03-01         NaN    NaN    NaN   NaN   NaN   NaN   NaN  NaN  NaN

    ...  家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  特例費用  旅行
36  ... NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1  貯金額合計  手取り月収  額面収入  健康保険  厚生年金  雇用保険  所得税  持株会  \
37 2023-04-01         NaN    NaN    NaN   NaN   NaN   NaN   NaN  NaN  NaN

    ...  家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  特例費用  旅行
37  ... NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1  貯金額合計  手取り月収  額面収入  健康保険  厚生年金  雇用保険  所得税  持株会  \
38 2023-05-01         NaN    NaN    NaN   NaN   NaN   NaN   NaN  NaN  NaN

    ...  家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  特例費用  旅行
38  ... NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1  貯金額合計  手取り月収  額面収入  健康保険  厚生年金  雇用保険  所得税  持株会  \
39 2023-06-01         NaN    NaN    NaN   NaN   NaN   NaN   NaN  NaN  NaN

    ...  家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  特例費用  旅行
39  ... NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1  貯金額合計  手取り月収  額面収入  健康保険  厚生年金  雇用保険  所得税  持株会  \
40 2023-07-01         NaN    NaN    NaN   NaN   NaN   NaN   NaN  NaN  NaN

    ...  家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  特例費用  旅行
40  ... NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1  貯金額合計  手取り月収  額面収入  健康保険  厚生年金  雇用保険  所得税  持株会  \
41 2023-08-01         NaN    NaN    NaN   NaN   NaN   NaN   NaN  NaN  NaN

    ...  家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  特例費用  旅行
41  ... NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1  貯金額合計  手取り月収  額面収入  健康保険  厚生年金  雇用保険  所得税  持株会  \
42 2023-09-01         NaN    NaN    NaN   NaN   NaN   NaN   NaN  NaN  NaN

    ...  家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  特例費用  旅行
42  ... NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1  貯金額合計  手取り月収  額面収入  健康保険  厚生年金  雇用保険  所得税  持株会  \
43 2023-10-01         NaN    NaN    NaN   NaN   NaN   NaN   NaN  NaN  NaN

    ...  家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  特例費用  旅行
43  ... NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1  貯金額合計  手取り月収  額面収入  健康保険  厚生年金  雇用保険  所得税  持株会  \
44 2023-11-01         NaN    NaN    NaN   NaN   NaN   NaN   NaN  NaN  NaN

    ...  家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  特例費用  旅行
44  ... NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1  貯金額合計  手取り月収  額面収入  健康保険  厚生年金  雇用保険  所得税  持株会  \
45 2023-12-01         NaN    NaN    NaN   NaN   NaN   NaN   NaN  NaN  NaN

    ...  家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  特例費用  旅行
45  ... NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1  貯金額合計  手取り月収  額面収入  健康保険  厚生年金  雇用保険  所得税  持株会  \
46 2024-01-01         NaN    NaN    NaN   NaN   NaN   NaN   NaN  NaN  NaN

    ...  家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  特例費用  旅行
46  ... NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1  貯金額合計  手取り月収  額面収入  健康保険  厚生年金  雇用保険  所得税  持株会  \
47 2024-02-01         NaN    NaN    NaN   NaN   NaN   NaN   NaN  NaN  NaN

    ...  家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  特例費用  旅行
47  ... NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1  貯金額合計  手取り月収  額面収入  健康保険  厚生年金  雇用保険  所得税  持株会  \
48 2024-03-01         NaN    NaN    NaN   NaN   NaN   NaN   NaN  NaN  NaN

    ...  家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  特例費用  旅行
48  ... NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1  貯金額合計  手取り月収  額面収入  健康保険  厚生年金  雇用保険  所得税  持株会  \
49 2024-04-01         NaN    NaN    NaN   NaN   NaN   NaN   NaN  NaN  NaN

    ...  家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  特例費用  旅行
49  ... NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1  貯金額合計  手取り月収  額面収入  健康保険  厚生年金  雇用保険  所得税  持株会  \
50 2024-05-01         NaN    NaN    NaN   NaN   NaN   NaN   NaN  NaN  NaN

    ...  家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  特例費用  旅行
50  ... NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1  貯金額合計  手取り月収  額面収入  健康保険  厚生年金  雇用保険  所得税  持株会  \
51 2024-06-01         NaN    NaN    NaN   NaN   NaN   NaN   NaN  NaN  NaN

    ...  家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  特例費用  旅行
51  ... NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1  貯金額合計  手取り月収  額面収入  健康保険  厚生年金  雇用保険  所得税  持株会  \
52 2024-07-01         NaN    NaN    NaN   NaN   NaN   NaN   NaN  NaN  NaN

    ...  家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  特例費用  旅行
52  ... NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1  貯金額合計  手取り月収  額面収入  健康保険  厚生年金  雇用保険  所得税  持株会  \
53 2024-08-01         NaN    NaN    NaN   NaN   NaN   NaN   NaN  NaN  NaN

    ...  家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  特例費用  旅行
53  ... NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1  貯金額合計  手取り月収  額面収入  健康保険  厚生年金  雇用保険  所得税  持株会  \
54 2024-09-01         NaN    NaN    NaN   NaN   NaN   NaN   NaN  NaN  NaN

    ...  家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  特例費用  旅行
54  ... NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1  貯金額合計  手取り月収  額面収入  健康保険  厚生年金  雇用保険  所得税  持株会  \
55 2024-10-01         NaN    NaN    NaN   NaN   NaN   NaN   NaN  NaN  NaN

    ...  家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  特例費用  旅行
55  ... NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1  貯金額合計  手取り月収  額面収入  健康保険  厚生年金  雇用保険  所得税  持株会  \
56 2024-11-01         NaN    NaN    NaN   NaN   NaN   NaN   NaN  NaN  NaN

    ...  家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  特例費用  旅行
56  ... NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN NaN

[1 rows x 26 columns]
           年月  Unnamed: 1  貯金額合計  手取り月収  額面収入  健康保険  厚生年金  雇用保険  所得税  持株会  \
57 2024-12-01         NaN    NaN    NaN   NaN   NaN   NaN   NaN  NaN  NaN

    ...  家賃  実家  交際費  飲食代  交通費  固定費  衣料費  その他  特例費用  旅行
57  ... NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN NaN

[1 rows x 26 columns]

In [24]:
for i in date:
    j = 1
    df_order_date = df_order[df_order['年月'] == i]
#     print(df_order_date)
    df_order_date.to_excel(export_file_path+'/' + str(j) + '.xlsx')
    j +=1